### ISSUE TITLE
文章目录

### ISSUE THREAD

**Issue by ghost** [yafoo/melog#10]
文章能不能加个目录功能呀，有个目录看的还是比较清楚

**Comment by yafoo** [comment]
你说的是一篇文章内容的目录索引吧？之前想过这个问题，考虑到只有部分长篇的文章需要目录索引，其他短篇博客、日志或图文文章，不太需要这个功能，所以就没做。后面我再想想，看怎么做一个，不过做的话，和可能是前端纯js来实现。

**Comment by ghost** [comment]
好的好的

**Comment by yafoo** [comment]
引入ztree的方式，你自己建个分支用吧，我就不往主分支合并了。

**Comment by ghost** [comment]
好的
